### ISSUE TITLE
testnet fails, can't find axios

### ISSUE THREAD

**Issue by bhazzard** [keppel/testnet#1]
When I try to run testnet, I get the following error:

`
blockchain brian.hazzard$ testnet
module.js:559
    throw err;
    ^

Error: Cannot find module 'axios'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/testnet/bin/testnet.js:8:13)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
`

I have axios installed locally, but I notice that testnet's package.json does not list axios as a dependency... not sure if that is the problem. I see that there is only one commit on this repo, is this being used successfully? Is it actively developed?

**Comment by keppel** [comment]
hey @bhazzard, thanks for catching that. I wouldn't recommend using this module right now, I'm going to deprecate it in favor of stuff that's coming soon that'll live in CLI in the main Lotion module.
